name: Publish Snap

on:
    workflow_dispatch: # Only enable manual runs for now

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # Step 1: Checkout the repository
            -   name: Checkout repository
                uses: actions/checkout@v4

            # Step 2: Set up Snapcraft
            -   name: Set up Snapcraft
                uses: snapcore/action-build@v1
                id: build
                with:
                    snapcraft-channel: stable
                continue-on-error: false

            # Step 3: Publish Snap
            -   name: Publish Snap
                uses: snapcore/action-publish@v1
                env:
                    SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
                with:
                    snap: ${{ steps.build.outputs.snap }}
                    release: stable
